import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
const inter = Inter({ subsets: ["latin"] });
import handsImage from "@/assets/Rectangle 5.jpg";

export const metadata: Metadata = {
  title: "CroudSourcing",
  description: "Generated by create next app",
  icons: handsImage.src,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
